# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Continous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-macOS:
    name: Test MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild build-for-testing -scheme SwiftAsyncAssert -destination "platform=macOS"
    - run: xcodebuild test-without-building -scheme SwiftAsyncAssert -destination "platform=macOS"
  test-iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild build-for-testing -scheme SwiftAsyncAssert -destination "platform=iOS Simulator,name=iPhone 13"
    - run: xcodebuild test-without-building -scheme SwiftAsyncAssert -destination "platform=iOS Simulator,name=iPhone 13"
  test-watchOS:
    name: Test watchOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: xcodebuild build-for-testing -scheme SwiftAsyncAssert -destination "platform=watchOS Simulator,name=Apple Watch Series 5 (40mm)"
    - run: xcodebuild test-without-building -scheme SwiftAsyncAssert -destination "platform=watchOS Simulator,name=Apple Watch Series 5 (40mm)"
