# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Continous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test macOS
      run: | 
        xcodebuild test -scheme SwiftAsyncAssert -destination "platform=macOS"
    - name: Test iOS
      run: | 
        xcodebuild test -scheme SwiftAsyncAssert -destination "platform=iOS Simulator,name=iPhone 13"
    - name: Test watchOS
      run: |
        xcodebuild test -scheme SwiftAsyncAssert -destination "platform=watchOS Simulator,name=Apple Watch Series 5 (40mm)"
